In [1]:
import pandas as pd

from dup_cleaner import dup_cleaner
from time_cleaner import time_cleaner

In [2]:
def read_soil(raw_file):

    df = pd.read_csv(raw_file, header=5, dtype = str)

    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

    # make the rest floats
    for col in df.columns:
        if col != 'Date' and col != 'Flag':
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # sort timestamps in case they are not in order
    df = df.sort_values(by='Date')

    return df

def read_met(raw_file):

    df = pd.read_csv(raw_file, header = 6, dtype = str)

    df = df.drop(df.index[0:2])

    df = df.drop(columns=['RECORD'])

    df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], errors='coerce')

    # make the rest floats
    for col in df.columns:
        if col != 'TIMESTAMP':
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # sort timestamps in case they are not in order
    df = df.sort_values(by='TIMESTAMP')

    return df

In [3]:
soil_path = r"C:\pyt\tx-soil-moisture\datasets\TxSON_data_2026-02-24\CB01.dat"
met_path = r"C:\pyt\tx-soil-moisture\datasets\TxSON_data_2026-02-24\CB04_met.dat"

soil_df = read_soil(soil_path)
met_df = read_met(met_path)

In [4]:
soil_df
# met_df

,Date,Ppt,SWC_5,SWC_10,SWC_20,SWC_50,T_5,T_10,T_20,T_50,Flag
0,2014-09-29 18:00:00,7.87,0.080,0.113,0.072,0.049,36.01,33.13,30.73,27.95,0
1,2014-09-29 19:00:00,0.00,0.079,0.113,0.073,0.049,34.23,33.07,30.92,27.93,0
2,2014-09-29 20:00:00,0.00,0.078,0.112,0.073,0.049,31.69,32.50,30.92,27.84,0
3,2014-09-29 21:00:00,0.00,0.077,0.111,0.073,0.049,29.41,31.69,30.79,27.79,0
4,2014-09-29 22:00:00,0.00,0.076,0.110,0.072,0.049,27.72,30.79,30.52,27.75,0
...,...,...,...,...,...,...,...,...,...,...,...
85247,2024-03-19 04:00:00,0.00,0.181,0.137,0.110,0.132,13.88,15.19,16.56,18.63,0
85248,2024-03-19 05:00:00,0.00,0.181,0.137,0.110,0.132,13.41,14.79,16.26,18.58,0
85249,2024-03-19 06:00:00,0.00,0.180,0.136,0.110,0.132,13.07,14.42,15.96,18.54,0
85250,2024-03-19 07:00:00,0.00,0.180,0.136,0.110,0.132,12.81,14.11,15.68,18.49,0
85251,2024-03-19 08:00:00,0.00,0.180,0.136,0.110,0.132,12.70,13.87,15.41,18.42,0

In [5]:
soil_df = soil_df.set_index('Date') # must have the timestamps as the index
met_df = met_df.set_index('TIMESTAMP')

dup_clean_soil = dup_cleaner(soil_df)
# dup_clean_met = dup_cleaner(met_df)

dup_clean_soil

,Ppt,SWC_5,SWC_10,SWC_20,SWC_50,T_5,T_10,T_20,T_50,Flag
Date,,,,,,,,,,
2014-09-29 18:00:00,7.87,0.080,0.113,0.072,0.049,36.01,33.13,30.73,27.95,0
2014-09-29 19:00:00,0.00,0.079,0.113,0.073,0.049,34.23,33.07,30.92,27.93,0
2014-09-29 20:00:00,0.00,0.078,0.112,0.073,0.049,31.69,32.50,30.92,27.84,0
2014-09-29 21:00:00,0.00,0.077,0.111,0.073,0.049,29.41,31.69,30.79,27.79,0
2014-09-29 22:00:00,0.00,0.076,0.110,0.072,0.049,27.72,30.79,30.52,27.75,0
...,...,...,...,...,...,...,...,...,...,...
2024-03-19 04:00:00,0.00,0.181,0.137,0.110,0.132,13.88,15.19,16.56,18.63,0
2024-03-19 05:00:00,0.00,0.181,0.137,0.110,0.132,13.41,14.79,16.26,18.58,0
2024-03-19 06:00:00,0.00,0.180,0.136,0.110,0.132,13.07,14.42,15.96,18.54,0
2024-03-19 07:00:00,0.00,0.180,0.136,0.110,0.132,12.81,14.11,15.68,18.49,0
2024-03-19 08:00:00,0.00,0.180,0.136,0.110,0.132,12.70,13.87,15.41,18.42,0

In [6]:
# drop flag
dup_clean_soil = dup_clean_soil.drop(columns=['Flag'])
clean_time_soil = time_cleaner(dup_clean_soil, extend_time = True)

# dup_clean_met = dup_clean_met.set_index('TIMESTAMP')
# clean_time_met = time_cleaner(dup_clean_met, extend_time = True)

Extending duplicate timestamps...

In [7]:
soil_df.tail()
# met_df.tail()

,Ppt,SWC_5,SWC_10,SWC_20,SWC_50,T_5,T_10,T_20,T_50,Flag
Date,,,,,,,,,,
2024-03-19 04:00:00,0.0,0.181,0.137,0.11,0.132,13.88,15.19,16.56,18.63,0
2024-03-19 05:00:00,0.0,0.181,0.137,0.11,0.132,13.41,14.79,16.26,18.58,0
2024-03-19 06:00:00,0.0,0.180,0.136,0.11,0.132,13.07,14.42,15.96,18.54,0
2024-03-19 07:00:00,0.0,0.180,0.136,0.11,0.132,12.81,14.11,15.68,18.49,0
2024-03-19 08:00:00,0.0,0.180,0.136,0.11,0.132,12.70,13.87,15.41,18.42,0

In [8]:
clean_time_soil.tail()
# clean_time_met.tail()

,Ppt,SWC_5,SWC_10,SWC_20,SWC_50,T_5,T_10,T_20,T_50
2024-03-19 14:00:00,0.0,0.181,0.137,0.11,0.132,13.88,15.19,16.56,18.63
2024-03-19 15:00:00,0.0,0.181,0.137,0.11,0.132,13.41,14.79,16.26,18.58
2024-03-19 16:00:00,0.0,0.180,0.136,0.11,0.132,13.07,14.42,15.96,18.54
2024-03-19 17:00:00,0.0,0.180,0.136,0.11,0.132,12.81,14.11,15.68,18.49
2024-03-19 18:00:00,0.0,0.180,0.136,0.11,0.132,12.70,13.87,15.41,18.42

In [10]:
# find the number of duplicate timestamps in the original dataframe

num_duplicates = dup_clean_soil.reset_index().duplicated(subset='Date').sum()
# num_duplicates = dup_clean_met.reset_index().duplicated(subset='TIMESTAMP').sum()

print(f"Number of duplicate timestamps in original dataframe, or the hour diff between the last timestamps: {num_duplicates}")

Number of duplicate timestamps in original dataframe, or the hour diff between the last timestamps: 10