In [1]:
#pip install pandas matplotlib scikit-learn numpy
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from analysis_helpers import create_dictionaries_from_csv, interactive_plot, generate_error_table, update_y_true

In [2]:
n = 4
files = [f"Trial{i}" for i in range(1, n+1)]
results = create_dictionaries_from_csv(files)
results = update_y_true(results)

TRIAL 1: 

Shape:= [Input Size = 24*7, Shift Amount = 24, Batch Size = 1024]

Target:= SWC_5

Station:= Station1

In [3]:
generate_error_table(results["Trial1"])

,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
column,,,
ar_bi_lstm,0.020104,0.119277,0.442040
shift_bl,0.038962,0.148098,0.530778
ar_lstm,0.018804,0.113614,0.424780
lstm,0.008721,0.048935,0.123390
bi_lstm,0.007591,0.049964,0.138450
cnn,0.031058,0.148634,0.507339

In [4]:
interactive_plot(results["Trial1"])

VBox(children=(Checkbox(value=True, description='ar_bi_lstm'), Checkbox(value=True, description='y_true'), Che…

FigureWidget({
    'data': [{'name': 'ar_bi_lstm',
              'type': 'scatter',
              'uid': '8175c608-87b3-4ead-9c4d-01eb42382f72',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.31174907, 0.30815035, 0.30580017, ..., 0.31640178, 0.31547442,
                          0.31416735])},
             {'name': 'y_true',
              'type': 'scatter',
              'uid': '6876f1c9-4a0c-4228-adff-4e385d5b9ade',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.22180451, 0.22180451, 0.22180451, ..., 0.28947368, 0.28947368,
                          0.28947368])},
             {'name': 'shift_bl',
              'type': 'scatter',
              'uid': 'a2a294e2-7bc7-4924-a873-306d38059c9d',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.7406015 , 0.73308271, 0.72932331, ..., 0.42105263, 0.42105263,
                          0.42105263])},
             {'name': 'ar_lstm',
              'type': 'scatter',
              'uid': 'd1594afc-9d60-4636-9157-1320dd983dfb',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.31469262, 0.31483355, 0.31407952, ..., 0.3240921 , 0.32639256,
                          0.32781813])},
             {'name': 'lstm',
              'type': 'scatter',
              'uid': '9ab0419b-1e62-4231-b760-68ad823d5bb1',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.17612273, 0.17284226, 0.16973798, ..., 0.23571075, 0.23301838,
                          0.23100501])},
             {'name': 'bi_lstm',
              'type': 'scatter',
              'uid': '1372b4de-2ed3-4421-8e19-926166708295',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.20293818, 0.20248596, 0.20104447, ..., 0.29881185, 0.29651266,
                          0.2947633 ])},
             {'name': 'cnn',
              'type': 'scatter',
              'uid': '6eb1f83f-6db0-4dec-843d-454e8c02d5ea',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.37957647, 0.38078627, 0.37614617, ..., 0.3765653 , 0.37531003,
                          0.3804113 ])}],
    'layout': {'height': 600, 'margin': {'b': 20, 'l': 20, 'r': 20, 't': 20}, 'template': '...'}
})

TRIAL 2:

Shape:= [Input Size = 24*7, Shift Amount = 24, Batch Size = 1024]

Target:= SWC_10

Station:= Station1

In [5]:
generate_error_table(results["Trial2"])

,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
column,,,
ar_bi_lstm,0.018117,0.119228,1.598594
shift_bl,0.021173,0.097726,1.074443
ar_lstm,0.020235,0.121414,1.796030
lstm,0.006329,0.067564,0.807888
bi_lstm,0.007352,0.073414,0.814144
cnn,0.020403,0.124087,1.394740

In [7]:
interactive_plot(results["Trial2"])

VBox(children=(Checkbox(value=True, description='ar_bi_lstm'), Checkbox(value=True, description='y_true'), Che…

FigureWidget({
    'data': [{'name': 'ar_bi_lstm',
              'type': 'scatter',
              'uid': '97ba51db-8661-4e47-b7ba-518fd0a80ce7',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.2661611 , 0.26601622, 0.26362628, ..., 0.27020046, 0.27117136,
                          0.27029344])},
             {'name': 'y_true',
              'type': 'scatter',
              'uid': '372f1034-551b-4f74-b8cf-77254dc59f2b',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.10747664, 0.10747664, 0.10747664, ..., 0.15420561, 0.14953271,
                          0.14953271])},
             {'name': 'shift_bl',
              'type': 'scatter',
              'uid': 'caaf59fd-fb0a-4dff-8a79-9bccc3984b3a',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.52336449, 0.51869159, 0.51401869, ..., 0.18691589, 0.18691589,
                          0.18691589])},
             {'name': 'ar_lstm',
              'type': 'scatter',
              'uid': 'bdedad14-773b-4c86-92b9-e9d4411a04f5',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.25666076, 0.2556736 , 0.25425237, ..., 0.24705864, 0.24822496,
                          0.24762021])},
             {'name': 'lstm',
              'type': 'scatter',
              'uid': '5f744033-3e3d-4b01-9427-ef901abca4a5',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.16119367, 0.15639856, 0.15280682, ..., 0.19602318, 0.19445764,
                          0.19287857])},
             {'name': 'bi_lstm',
              'type': 'scatter',
              'uid': '467aeb81-360b-4e46-8f4d-3a39f4a91ae9',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.42723006, 0.4284403 , 0.428283  , ..., 0.21930063, 0.21511441,
                          0.2102213 ])},
             {'name': 'cnn',
              'type': 'scatter',
              'uid': '251c2078-c981-461e-90a9-f1a0da13d740',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.2559445 , 0.2518379 , 0.25246716, ..., 0.24549295, 0.25806487,
                          0.2684422 ])}],
    'layout': {'height': 600, 'margin': {'b': 20, 'l': 20, 'r': 20, 't': 20}, 'template': '...'}
})

TRIAL 3:

Shape:= [Input Size = 24*7, Shift Amount = 24, Batch Size = 1024]

Target:= SWC_20

Station:= Station1

In [8]:
generate_error_table(results["Trial3"])

,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
column,,,
ar_bi_lstm,0.017136,0.111070,0.937145
shift_bl,0.028327,0.107270,0.659643
ar_lstm,0.017426,0.111828,0.944489
lstm,0.005582,0.044801,0.323104
bi_lstm,0.004451,0.032263,0.196056
cnn,0.026054,0.134629,0.970489

In [9]:
interactive_plot(results["Trial3"])

VBox(children=(Checkbox(value=True, description='ar_bi_lstm'), Checkbox(value=True, description='y_true'), Che…

FigureWidget({
    'data': [{'name': 'ar_bi_lstm',
              'type': 'scatter',
              'uid': '0e8bfaa0-13e5-4225-bf01-283045f8ccb1',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.26511073, 0.26602197, 0.26635426, ..., 0.20899089, 0.21183662,
                          0.21251051])},
             {'name': 'y_true',
              'type': 'scatter',
              'uid': 'e6b1a6f5-aa91-40ab-9897-b01e68335b1d',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.18120805, 0.17449664, 0.17449664, ..., 0.04697987, 0.04697987,
                          0.04697987])},
             {'name': 'shift_bl',
              'type': 'scatter',
              'uid': '0996ec1d-3969-47e5-a0f3-b37ccec8b36b',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.5704698 , 0.5704698 , 0.5704698 , ..., 0.06711409, 0.06711409,
                          0.06711409])},
             {'name': 'ar_lstm',
              'type': 'scatter',
              'uid': '65c1fde2-820d-41b5-8836-0fefb3b2537d',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.27287653, 0.271658  , 0.27026087, ..., 0.20853223, 0.20875186,
                          0.20797017])},
             {'name': 'lstm',
              'type': 'scatter',
              'uid': '2a0807c3-f9b0-4f47-9fbe-dcb1edc27e84',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.21254236, 0.20947625, 0.20691527, ..., 0.06777834, 0.06691497,
                          0.06585579])},
             {'name': 'bi_lstm',
              'type': 'scatter',
              'uid': 'a20b91fd-4c24-4ab0-a213-25596af24b4e',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.15125829, 0.14977261, 0.14818215, ..., 0.04121407, 0.04036748,
                          0.03992601])},
             {'name': 'cnn',
              'type': 'scatter',
              'uid': 'ad6bd92e-abda-42ee-9ca6-0b55d5e2ad0f',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.27686217, 0.2848266 , 0.2925847 , ..., 0.22137278, 0.22598958,
                          0.234896  ])}],
    'layout': {'height': 600, 'margin': {'b': 20, 'l': 20, 'r': 20, 't': 20}, 'template': '...'}
})

TRIAL 4:

Shape:= [Input Size = 24*7, Shift Amount = 24, Batch Size = 1024]

Target:= SWC_50

Station:= Station1

In [10]:
generate_error_table(results["Trial4"])

,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
column,,,
ar_bi_lstm,0.006023,0.059426,0.351286
shift_bl,0.020544,0.087663,0.457978
ar_lstm,0.006075,0.061161,0.406196
lstm,0.002895,0.031739,0.155234
bi_lstm,0.002040,0.023095,0.140186
cnn,0.020894,0.118052,0.764783

In [11]:
interactive_plot(results["Trial4"])

VBox(children=(Checkbox(value=True, description='ar_bi_lstm'), Checkbox(value=True, description='y_true'), Che…

FigureWidget({
    'data': [{'name': 'ar_bi_lstm',
              'type': 'scatter',
              'uid': 'e61ab6ce-e62d-4fd7-b258-318f1c9804dc',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.16438045, 0.16335921, 0.16119832, ..., 0.13377216, 0.13420632,
                          0.13336259])},
             {'name': 'y_true',
              'type': 'scatter',
              'uid': 'c4a044f4-6c1c-467d-bfd5-a0223cef119a',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.09876543, 0.09876543, 0.09876543, ..., 0.07407407, 0.07407407,
                          0.07407407])},
             {'name': 'shift_bl',
              'type': 'scatter',
              'uid': '51a9e3f1-d2ec-4026-a3e1-3c9e31ce29db',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.11111111, 0.11111111, 0.11111111, ..., 0.07407407, 0.07407407,
                          0.07407407])},
             {'name': 'ar_lstm',
              'type': 'scatter',
              'uid': '5ff05983-3573-4fdf-a2fa-b1c12e0f61ec',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.1730633 , 0.17365399, 0.17419976, ..., 0.13410068, 0.13427757,
                          0.13456988])},
             {'name': 'lstm',
              'type': 'scatter',
              'uid': '0406f4a8-77e6-443f-80b3-f0cae0fe8715',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.05089346, 0.05171502, 0.05268441, ..., 0.06041092, 0.05918619,
                          0.05807567])},
             {'name': 'bi_lstm',
              'type': 'scatter',
              'uid': '6f9a339a-5cc4-4829-93e7-758495d282e8',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.07689368, 0.07713316, 0.07690729, ..., 0.06450835, 0.06314223,
                          0.06088509])},
             {'name': 'cnn',
              'type': 'scatter',
              'uid': 'e71e4ef9-8c25-4bd3-a097-cc307f8e3557',
              'visible': True,
              'x': array([   0,    1,    2, ..., 8189, 8190, 8191]),
              'y': array([0.22111574, 0.20920761, 0.19282635, ..., 0.13389038, 0.12553261,
                          0.12388872])}],
    'layout': {'height': 600, 'margin': {'b': 20, 'l': 20, 'r': 20, 't': 20}, 'template': '...'}
})